
export enum ErrorCode {
   VALIDATION = 'VALIDATION',
   INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
   BAD_REQUEST = 'BAD_REQUEST',
   EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',

   INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
   INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
   RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

   EXPIRED_CODE_EXCEPTION_ERROR = 'EXPIRED_CODE_EXCEPTION_ERROR',

   CODE_MISMATCH_EXCEPTION_ERROR = 'CODE_MISMATCH_EXCEPTION_ERROR'

}
